version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_USERNAME: ***
      SPRING_DATASOURCE_PASSWORD: ***
      SPRING_DATASOURCE_URL: ***

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ***
      POSTGRES_PASSWORD: ***
      POSTGRES_DB: ***
